= Boundary condition
:icons: font
:stem: latexmath
:feelpp: Feel++
:nofooter:
:toc: left
:bibtex-file: ibat.bib

To solve a [blue]#_fluid mechanics_# problem, we use physical laws to find the mathematical 
equations which describe the physical properties of the fluid, such as velocity, 
temperature, pressure, density and viscosity. It is assumed that the fluid is incompressible, 
it means that the volume of the fluid cannot be reduced by an increase of pressure. 
Theses equations are called the governing equations of CFD:

== Continuity equation

Consider the  fundamental principle of physics proposed by Antoine  Lavoisier, which gives theintergral
 form of the mass conservation equation:

[sidebar]
.Mass conservation equation 
--
[stem]
++++
\frac{\partial}{\partial t} \int_\Omega \rho d \omega +
\int_{\partial \Omega} \rho v \cdot \vec nd \sigma =
0 \qquad \forall v \in \mathbb R
++++
--

where stem:[\rho(kg/m)] is the density in the domain stem:[\Omega],
stem:[v(m/s)] is the velocity of the fluid and stem:[n] the unitnormal vector to the boundary stem:[\partial \Omega].

Consider also:

[sidebar]
.Gausse divergence theorem:
--
[stem]
++++
\int_\Omega\nabla\cdot vd\omega=\int_{\partial\Omega}v\cdot\vec n d\sigma\qquad\forall v\in\mathbb R
++++
--

Using Gauss divergence theorem in the mass conservation equation, 
we obtain the differential form,which is the continuity equation:

[sidebar]
.Continuity equation
--
[stem]
++++
\frac{\partial\rho}{\partial t}+\nabla\cdot(\rho v)=0
++++
--

== Movement equation

Newton’s second law states that the force of a moving object is equivalent to it's rate of 
change of movement.  In fluid mechanics, the movement theorem is :

[sidebar]
.Movement theorem:
--
[stem]
++++
\sum\vec F_{ext}=\int_\Omega\frac{\partial(\rho v)}{\partial t}d\omega+\int_{\partial\Omega}(\rho\vec v)\cdot(\vec v\cdot\vec n)d\sigma
++++
--

And it was converted to differential form by the french mathematician Cauchy, 
with the applicationof the divergence theorem.

The result is the movement equation :

[sidebar]
.Movement equation
--
[stem]
++++
\rho\big(\frac{\partial v}{\partial t}+v\cdot\nabla v\big)=-\nabla p+\mu\Delta v+\rho g
++++
--

where stem:[p (Pa)] is the pressure, stem:[\mu] is the dynamic viscosity and stem:[g] is the external
forces acting on the fluid, such as gravity.

= Energy equation

[sidebar]
.Energy equation
--
[stem]
++++
\frac{\partial(\rho h-p)}{\partial t}+\nabla(\rho vh)=\nabla\big((\mu+\frac{\mu_t}{\sigma_t})\nabla h\big)-S_h
++++
--
where stem:[h = U+pV(J)] is the internal energy of the system, V is the volume, stem:[\mu_{t}] 
is the thurbulence viscosity, stem:[\sigma_t] is a constant and stem:[S_h]
 is the volumetric heat source.
