== Documentation

=== Contents

1 <<introduction,Introduction>> +
2 <<Computational_Fluid_Dynamics,Computational Fluid Dynamics>> +
3 <<Computational_Solid_Mechanics,Computational Solid Mechanics>>

[[introduction]]
=== Introduction
Regarding problems of <<Computational_Fluid_Dynamics,Computational Fluid Dynamics>> (<<Computational_Fluid_Dynamics,CFD>>) and <<Computational_Solid_Mechanics,Computational Solid Mechanics>> (<<Computational_Solid_Mechanics,CSM>>), there is a solving method to follow, including phases such as the verification phase, or the validation phase. +
This part deals with the validation phase, the aim is to check if the solved problem is the right one and not another, this can be done by comparing the results to a database.

[[Computational_Fluid_Dynamics]]
=== Computational Fluid Dynamics (CFD)

==== Model

==== Examples

[[Computational_Solid_Mechanics]]
=== Computational Solid Mechanics (CSM)

==== Model

==== Examples


=== Context
==== Computational Fluid Dynamics

For *CFD* we constat that it supports both the incompressible Navier-Stokes and the Stokes equations. 
To do well the projet, it will based on properties namely the *density* and *viscosity*, 
and finally, we will not own the *Boundary Conditions*.

==== Computational Solid Mechanics
It works properly with equations like  *Linear elasticity*
and *Hyper-elasticity*. We can also use Axisymmetric reduced model.
