= Introduction to Computational Fluid Dynamics
:stem: latexmath

== What is a fluid ?

A fluid is a substance that flows (in other words, it takes the shape of its container) and does not resist deformation (i.e. slips when moved). The terms fluid and liquid are often used interchangeably, but technically, the term fluid can refer to both a liquid and a gas.

The distinction between liquids and gases can affect how the fluid is modeled, but both have the same basic fluid formulae and comparable properties.

== Macroscopic properties of a fluid:

1.Dynamic viscosity: 

The viscosity of a fluid characterizes its resistance to a  speed of deformation (movement) caused by the application of a constraint (Force/surface).

2.Compressibility:

The ability of a fluid to undergo significant variations in density when applying a pressure step stem:[\Delta P] or a temperature variation stem:[\Delta T].

Two coefficients are used:

- isothermal compressibility coefficient: stem:[K_t]

- Coefficient of thermal expansion at constant pressure beta.

3.Thermal diffusion:

The quantity 

[stem]
++++
q = \frac{Q}{A}
++++

is called heat flux density. It is a thermal power (Watts) exchanged per unit of surface area and is set: 

[stem]
++++
q = \frac{Q}{A} = - \lambda \frac{T1-T0}{H}
++++

The positive number stem:[\lambda] is called the coefficient of thermal conductivity, it is expressed in W.m/K.

== CFD insight

Computational fluid dynamics (CFD) is one of the most quickly emerging fields in applied sciences.

CFD mainly deals with the numerical analysis of fluid dynamics problems, which embodies differential calculus. The equations involved in fluid dynamics are Navier–Stokes equations. Until now, solutions to Navier–Stokes equations have not been explicitly found except for some cases such as Poiseuille flow, Couette flow, and Stokes flow with certain assumptions.

Thus, CFD is the process of converting the partial differential equations of fluid dynamics into simple algebraic equations and then solving them numerically to obtain some meaningful results.

== CFD prosses

The CFD is based on three essential processes:

* Pre-processing

This is the most important phase and it is also called the meshing phase where we have to create an understandable topology adapted to our field of study.

* Solving

This phase consists in solving the guiding equations of the flow, this work is done by the computer.

* Post-processing: 

This step is based on the visualization and interpretation of the results for the development or optimization of the product. Finally for the validation of the results they are compared with the experimental data.

All three processes are interdependent

== Generalities about the Stokes problem
=== Navier-Stokes equation:

The Navier-Stokes equations are a system of non linear partial differential equations which describe the movement of fluids in a continuous medium, it is demonstrated from a balance of momentum per unit volume for an incompressible fluid it is given in the form:

[sidebar]
.Equation of Navier-Stokes 
--
[stem]
++++
\begin{cases}
\displaystyle
 \overrightarrow{\nabla}.\overrightarrow{v}=0~~~~~~~~(1)\\

 \rho \frac{\partial \overrightarrow{v}}{\partial t} + \rho(\overrightarrow{v}.\overrightarrow{\nabla})\overrightarrow{v}=-\overrightarrow{\nabla}p+\rho \overrightarrow{f}_{ext}+\mu \Delta \overrightarrow{v}     ~~~~~~~~(2) \\
\end{cases}
++++

where:

* stem:[\rho]: fluid density.
* stem:[p(\overrightarrow{r},t)]: pressure, it is the isotropic part of the stress tensor.
* stem:[-\overrightarrow{\nabla}p]:  normal stresses related to pressure forces.
* stem:[\overrightarrow{f}_{ext}(\overrightarrow{r},t)]: force per unit mass.
--
The first equation (1) is zero divergence equation of the velocity field stem:[\overrightarrow{v}(\overrightarrow{r},t)], it ensures the incompressibility of the fluid. Each term of the second equation (2) represents a force per unit of volume such as.

When we divide the balance equation (2) of forces per unit volume stem:[\rho], we get a balance of forces per unit mass, which can also be interpreted as a velocity transport equation:

[sidebar]
.Velocity Transport Equation 
--
[stem]
++++
\frac{\partial \overrightarrow{v}}{\partial t} + (\overrightarrow{v}.\overrightarrow{\nabla})\overrightarrow{v} = -\frac{1}{\rho}\overrightarrow{\nabla}(p-p_{0})+ V \Delta \overrightarrow{v}
++++

where: 

* stem:[V=\frac{\mu}{\rho}]: kinematic viscosity of the fluid 
* stem:[V \nabla \overrightarrow{v}]: linear term, he represents the movement quantity transport.
* stem:[p_0]: pressure in the absence of flow.
--

===  Reynolds number
The Reynolds number is a dimensionless quantity that gives the ratio between the inertial forces and the viscous forces that intervene in the flow.

We will write the Navier-Stokes equation using dimensionless combinations (which will be noted by premiums) of the different sizes involved. Let L and U be the scales respective size and flow velocity, we have:

stem:[\overrightarrow{r}=L\overrightarrow{r}^{'}]; 
stem:[\overrightarrow{v}=L\overrightarrow{v}^{'}];
stem:[p-p_{0}=(\rho U^{2})p^{'}];
stem:[t=\frac{L}{U}t^{'}]

So the Navier-Stokes equation becomes:
[stem]
++++
\frac{\partial \overrightarrow{v}^{'}}{\partial t^{'}} + (\overrightarrow{v}^{'}.\overrightarrow{\nabla}^{'})\overrightarrow{v}^{'}=-\overrightarrow{\nabla}^{'}p^{'}+  
\frac{1}{Re}\Delta^{'} \overrightarrow{v}^{'}
++++

The expression of Rynolds number is as follows

[sidebar]
.Rynolds number
--
[stem]
++++
Re= \frac {\rho UL}{\mu}
++++
--

We recognize the two characteristic times necessary to transport the movement over a length L by diffusion and by convection. Transportation will be the shortest time thus dominating, the Reynolds number is the relationship between convective and diffusive effects:

[stem]
++++
Re= \frac{effects_{convective}}{effects_{diffusive}}
++++

It is also often useful to understand the Reynolds number as the relationship between the terms of inertia and viscous forces of the Navier-Stokes (2) equation such as:

[stem]
++++
Re= \frac{inertia_{forces}}{viscous_{forces}}
++++


The Stokes problem is involved in a very large number of physical applications, and one of the great originalities of the Stokes problem is its reversibility over time. This means that a swimmer in a Stokes fluid has to break the symmetry of its movement to move forward.

== Governing Equations

To solve a [blue]#_fluid mechanics_# problem, we use physical laws to find the mathematical 
equations which describe the physical properties of the fluid, such as velocity, 
temperature, pressure, density and viscosity. It is assumed that the fluid is incompressible, 
it means that the volume of the fluid cannot be reduced by an increase of pressure. 
Theses equations are called the governing equations of CFD:

=== Continuity equation
Consider the  fundamental principle of physics proposed by Antoine  Lavoisier, which gives theintergral form of the mass conservation equation:

[sidebar]
.Mass conservation equation 
--
[stem]
++++
\frac{\partial}{\partial t} \int_\Omega \rho d \omega +
\int_{\partial \Omega} \rho v \cdot \vec nd \sigma =
0 \qquad \forall v \in \mathbb R
++++
--

where stem:[\rho(kg/m)] is the density in the domain stem:[\Omega],
stem:[v(m/s)] is the velocity of the fluid and stem:[n] the unitnormal vector to the boundary stem:[\partial \Omega].

Consider also:

[sidebar]
.Gausse divergence theorem:
--
[stem]
++++
\int_\Omega\nabla\cdot vd\omega=\int_{\partial\Omega}v\cdot\vec n d\sigma\qquad\forall v\in\mathbb R
++++
--

Using Gauss divergence theorem in the mass conservation equation, 
we obtain the differential form,which is the continuity equation:

[sidebar]
.Continuity equation
--
[stem]
++++
\frac{\partial\rho}{\partial t}+\nabla\cdot(\rho v)=0
++++
--

=== Movement equation
Newton’s second law states that the force of a moving object is equivalent to it's rate of 
change of movement.  In fluid mechanics, the movement theorem is :

[sidebar]
.Movement theorem:
--
[stem]
++++
\sum\vec f_{ext}=\int_\Omega\frac{\partial(\rho v)}{\partial t}d\omega+\int_{\partial\Omega}(\rho\vec v)\cdot(\vec v\cdot\vec n)d\sigma
++++
--

And it was converted to differential form by the french mathematician Cauchy, 
with the applicationof the divergence theorem.

The result is the movement equation :

[sidebar]
.Movement equation
--
[stem]
++++
\rho\big(\frac{\partial v}{\partial t}+v\cdot\nabla v\big)=-\nabla p+\mu\Delta v+\rho g
++++
--

where stem:[p (Pa)] is the pressure, stem:[\mu] is the dynamic viscosity and stem:[g] is the external forces acting on the fluid, such as gravity.

=== Energy equation

[sidebar]
.Energy equation
--
[stem]
++++
\frac{\partial(\rho h-p)}{\partial t}+\nabla(\rho vh)=\nabla\big((\mu+\frac{\mu_t}{\sigma_t})\nabla h\big)-S_h
++++
--

where stem:[h = U+pV(J)] is the internal energy of the system, V is the volume, stem:[\mu_t] 
is the thurbulence viscosity, stem:[\sigma_t] is a constant and stem:[S_h] is the volumetric heat source.

=== Simutaion Model 
==== `Backward-Facing Step (BFS)`
Backward-Facing Step (BFS) flow is one representative model for separation flows, which can be widely seen in:

- Aerodynamic flows +
- Engine flows +
- Heat transfer systems + 
- Flow around buildings +

The <<BFS>> is a very popular reference and validation model for Computational Fluid Dynamics (CFD) simulations because of the availability of a good number of experimental data.
Flow separation depends on several parameters such as BFS geometry, inlet and outlet conditions, turbulent intensity, as well as heat transfer conditions.
Although the geometry is very simple, the flow may have interesting separation regions, which also makes it an ideal candidate for testing numerical boundary conditions.



[bibliography]
== Bibliography 

* L.Chen, A review of Backward-Facing Step (BFS) flow mechanisms, heat transfer and control, June 2018, Pages 194-216

* S.Jamshed, Introduction to CFD, December 2015











