= Results
:icons: font
:stem: latexmath
:feelpp: Feel++
:nofooter:
:toc: left
:bibtex-file: ibat.bib

NOTE: For the readability of the results, we have separated the calculations for `Re= 389` and those for
`Re=1095`.

== `Running the case`:

The command line to run this cases is

[source,sh]
----
mpirun -np 4 feelpp_toolbox_fluid--config-file laminar.cfg--fluid.snes-monitor=1--fluid.gmsh.hsize=3e-4
----

++++
<button class="btn" data-clipboard-target="#command-line-cfd1">
Copy command line to clipboard
</button>
++++

Once the command is executed the results are exported to ParaView for viewing the flow by executing:

[source,sh]
----
rsync -avz atlas.math.unistra.fr:/feel
----

++++
<button class="btn" data-clipboard-target="#command-line-cfd1">
Copy command line to clipboard
</button>
++++

== Results for `Re=389`

In this part the problem is dealt with in a stationary frame.

NOTE: The solution does not depend on the
time, more precisely the flow profile is to long at the points where the flow variation is not visible.

=== Data files
 
==== `JSON-file`:

[source,json]
.laminar.json
----
{
    "Name": "Laminar, Isothermal Backward Facing Step Benchmark",
    "ShortName":"ecoulementstationnaire",
    "Models":
    {
         "equations": "Navier-Stokes"
    },
    "Parameters":
    {
        "h":"5.2e-3",       
        "s":"4.9e-3",       
        "uave":"0.54433"          <1>
    },
    "Materials":
    {
        "omega":
        {
            "rho":"1.23",
            "mu":"1.79e-5"
        }
    }, 
    "BoundaryConditions":
    {
        "velocity":
        {
            "Dirichlet":
            {
                "inlet":
                {
                    "expr":"{6*uave*((y-s)/h)*(1-((y-s)/h)),0}:uave:s:h:y"
                },
                "wall1":
                {
                    "expr":"{0,0}"
                },
                "wall2":
                {
                    "expr":"{0,0}"
                },
                "wall3":
                {
                    "expr":"{0,0}"
                }
            }
        },
        "fluid":
        {
            "outlet":
            {
                "outlet":
                {
                    "expr":"0" 
                }
            }
        }
    },
    "PostProcess":
    {   
        "Exports":
        {
            "fields":["velocity"]
        }

    }
}
----

<1> `uave` is the average velocity for `Re=389`.

==== `CFG-file`:

[source,cfg]
.laminar.cfg
----
directory=resulats/stationnaire389/P1

[case]
discretization= P2P1G1
dimension=2

[fluid]
filename=$cfgdir/laminar.json
mesh.filename=$cfgdir/laminar.geo
gmsh.hsize=0.0005

solver= Newton 
linearsystem-cst-update=false
jacobian-linear-update=false

snes-monitor=true
pc-type= gams
snes-rtol=1e-10

[ts]
steady=true
----

== Results for `Re=1095`

To have a stationary solution when Re=1095 the problem has to be treated in an unstationary
frame.
 
NOTE:In this case the solution will depend on time.

=== Data files
 
==== `JSON-file`:

[source,json]
.laminar.json
----
{
    "Name": "Laminar, Isothermal Backward Facing Step Benchmark",
    "ShortName":"ecoulementstationnaire",
    "Models":
    {
        "equations":"Navier-Stokes"
    },
    "Parameters":
    {
        "h":"5.2e-3",
        "s":"4.9e-3",
        "uave":"1.5322"        <1>
    },
    "Materials":
    {
        "omega":
        {
            "rho":"1.23",
            "mu":"1.79e-5"
        }
    },
    "BoundaryConditions":
    {
        "velocity":
        {
            "Dirichlet":
            {
                "inlet":
                {
                    "expr":"{6*uave*((y-s)/h)*(1-((y-s)/h)),0}:uave:s:h:y"
                },
                "wall1":
                {
                    "expr":"{0,0}"
                },
                "wall2":
                {
                    "expr":"{0,0}"
                },
                "wall3":
                {
                    "expr":"{0,0}"
                }
            }

        },
        "fluid":
        {
            "outlet":
            {
                "outlet":
                {
                    "expr":"0" 
                }
            }
        }
    },
    "PostProcess":
    {
        "Exports":
        {
            "fields":["velocity"]
        }
    }
}
----

<1> `uave` is the average velocity for `Re=1095`.

==== `CFG-file`:

[source,cfg]
.laminar.cfg
----
directory=resulats/instationnaire1095/P1

[case]
discretization= P2P1G1
dimension=2

[fluid]
filename=$cfgdir/laminar.json
mesh.filename=$cfgdir/lami.geo
gmsh.hsize=0.0005

solver= Newton
linearsystem-cst-update=false
jacobian-linear-update=false

ts.steady=true
snes-monitor=true
pc-type= gams

[fluid.bdf]
order=2

[ts]
time-step=0.1
time-final=10
----





















