= Presentation of the problem
:stem: latexmath

== Introduction
Regarding problems of <<Computational_Fluid_Dynamics,Computational Fluid Dynamics>> (<<Computational_Fluid_Dynamics,CFD>>) and <<Computational_Solid_Mechanics,Computational Solid Mechanics>> (<<Computational_Solid_Mechanics,CSM>>), there is a solving method to follow, including phases such as the verification phase, or the validation phase. +
This part deals with the validation phase, the aim is to check if the solved problem is the right one and not another, this can be done by comparing the results to a database.


== Problem
This project consists in carrying out a simulation of internal, laminar, incompressible flow in a channel on a backward facing stape <<Backward-Facing Step,Backward-Facing Step>> (<<Backward-Facing Step,BFS>>). Flow separation is a common and interesting phenomenon in fluid mechanics with significant effects in practical application. Among them the backward-facing step flow which represents a very popular reference and validation test for <<Computational_Fluid_Dynamics,Computational Fluid Dynamics>> (<<Computational_Fluid_Dynamics,CFD>>) simulations due to the availability of a good number of good experimental data.


== Methodology
To solve a <<CFD>> problem, we mainly go through three steps: +

1. Definition of a geometry and a mesh discretizing the computational domain and the numerical methods used. +

2. Numerical solution of the problem +

3. Exploitation of the results +

== Simutaion Model 
=== `Backward-Facing Step (BFS)`
Among the representative models of separation flows is (<<BFS>>),which can be seen in :

- Aerodynamic flows +
- Engine flows +
- Heat transfer systems + 
- Flow around buildings +

The <<BFS>> is a very popular reference and validation model for Computational Fluid Dynamics (CFD) simulations because of the availability of a good number of experimental data.
Flow separation depends on several parameters such as BFS geometry, inlet and outlet conditions, turbulent intensity, as well as heat transfer conditions.
Although the geometry is very simple, the flow may have interesting separation regions, which also makes it an ideal candidate for testing numerical boundary conditions.



== Objectives
The different objectives are :

1. Compare the results of the velocity profile with numerical results from the literature.+

2. Comparison of the flow attachment location with available experimental data.+

3. Prescribe input condition data.+








