name: CI

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: buildkite/trigger-pipeline-action@v1.2.0
      env:
        BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
        PIPELINE: "feelpp/cemosis-docs"
        COMMIT: "HEAD"
        BRANCH: "master"
        MESSAGE: ":github: [Triggered from a GitHub Action by Feelpp CFD Project] ${{ github.event.head_commit.message }}"

